#include "primitives/group.h"
#include "primitives/group-z-ordered.h"
#include "primitives/svg.h"
#include "primitives/circle.h"
#include "primitives/rect.h"
#include "primitives/line.h"
#include "primitives/poly.h"
#include "primitives/path.h"
#include "primitives/text.h"
#include "primitives/image.h"

#include "plot/plot-function.h"
#include "plot/plot-curve.h"
#include "plot/plot-curve-3d.h"
#include "plot/graph-3d.h"
#include "plot/graph-2d.h"
#include "plot/project.h"

#include "scripts/window-reload.h"
#include "scripts/set-timeout.h"
#include "scripts/set-interval.h"
#include "scripts/reload.h"
#include "scripts/for-all.h"

#include "utils/browse.h"
#include "utils/watch.h"
